// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application

import (
	"context"

	"github.com/PavelsDenisovs/feature-flag-gatekeeper/internal/flag/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FetchFlagByKey provides a mock function for the type MockRepository
func (_mock *MockRepository) FetchFlagByKey(ctx context.Context, flagKey string) (domain.Flag, error) {
	ret := _mock.Called(ctx, flagKey)

	if len(ret) == 0 {
		panic("no return value specified for FetchFlagByKey")
	}

	var r0 domain.Flag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Flag, error)); ok {
		return returnFunc(ctx, flagKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Flag); ok {
		r0 = returnFunc(ctx, flagKey)
	} else {
		r0 = ret.Get(0).(domain.Flag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, flagKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FetchFlagByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFlagByKey'
type MockRepository_FetchFlagByKey_Call struct {
	*mock.Call
}

// FetchFlagByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - flagKey string
func (_e *MockRepository_Expecter) FetchFlagByKey(ctx interface{}, flagKey interface{}) *MockRepository_FetchFlagByKey_Call {
	return &MockRepository_FetchFlagByKey_Call{Call: _e.mock.On("FetchFlagByKey", ctx, flagKey)}
}

func (_c *MockRepository_FetchFlagByKey_Call) Run(run func(ctx context.Context, flagKey string)) *MockRepository_FetchFlagByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FetchFlagByKey_Call) Return(flag domain.Flag, err error) *MockRepository_FetchFlagByKey_Call {
	_c.Call.Return(flag, err)
	return _c
}

func (_c *MockRepository_FetchFlagByKey_Call) RunAndReturn(run func(ctx context.Context, flagKey string) (domain.Flag, error)) *MockRepository_FetchFlagByKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockService
func (_mock *MockService) Evaluate(ctx context.Context, req EvaluateRequest) (EvaluateResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 EvaluateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, EvaluateRequest) (EvaluateResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, EvaluateRequest) EvaluateResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(EvaluateResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, EvaluateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockService_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - req EvaluateRequest
func (_e *MockService_Expecter) Evaluate(ctx interface{}, req interface{}) *MockService_Evaluate_Call {
	return &MockService_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, req)}
}

func (_c *MockService_Evaluate_Call) Run(run func(ctx context.Context, req EvaluateRequest)) *MockService_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 EvaluateRequest
		if args[1] != nil {
			arg1 = args[1].(EvaluateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Evaluate_Call) Return(res EvaluateResponse, err error) *MockService_Evaluate_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockService_Evaluate_Call) RunAndReturn(run func(ctx context.Context, req EvaluateRequest) (EvaluateResponse, error)) *MockService_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}
